### ISSUE TITLE
docker模式下使用官方提供的docker-compose.yaml如何给mysql设置密码

### ISSUE THREAD

**Issue by QQ897878763** [ctripcorp/apollo.net#162]
更新docker-compose内的mysql容器的user表密码如下：
```
update mysql.user set authentication_string=password('apollo@@@') where user='root' and HOST = '%' ;
```
更新docker-compose.yml后内容如下：
```
version: '2'

services:
  apollo-quick-start:
    image: nobodyiam/apollo-quick-start
    container_name: apollo-quick-start
    restart: unless-stopped
    environment:
      - EUREKA_INSTANCE_IP_ADDRESS= 'ip'
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - spring_datasource_url=jdbc:mysql://ip:13306/ApolloPortalDB?characterEncoding=utf8
      - spring_datasource_username=root
      - spring_datasource_password=apollo@@@
    depends_on:
      - apollo-db
    ports:
      - "8080:8080"
      - "8090:8090"
      - "8070:8070"
    links:
      - apollo-db

  apollo-db:
    image: mysql:5.7
    container_name: apollo-db
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_USER: root
      MYSQL_PASSWORD: apollo@@@
      MYSQL_ROOT_PASSWORD: apollo@@@
    depends_on:
      - apollo-dbdata
    ports:
      - "13306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    volumes_from:
      - apollo-dbdata

  apollo-dbdata:
    image: alpine:latest
    container_name: apollo-dbdata
    volumes:
      - /var/lib/mysql

```
发现执行docker-compose up -d后apollo-quick-start服务无法启动，服务注册中心也无法启动。尝试将密码变更为空就可以，不过这样不安全，希望@nobodyiam 大佬提供下解决思路 谢谢
